Added functionality for rendering generated graphs in the front-end
neo4j-labs/llm-graph-builder pull request #106
Opened 2024-03-12 09:45 UTC by nielsdejong

New features:
- In the table view, added a button 'View' that is enabled after the graph generation completes.
- The button opens up a modal, which runs a Cypher query using the selected document name.
- The result of the query is a list of nodes and relationships that are related to the document (neighbourhood of max. depth 3)
- Results are rendered as a graph visualization using the NVL library. Captions, icons and styling is inferred from the labels and properties in the graph.

2024-03-12 09:53 UTC, jexp approved these changes
Looks good to me for a per-file view

2024-03-12 10:26 UTC, praveshkumar1988 approved these changes
Approved

2024-03-12 13:33 UTC, msenechal requested changes

2024-03-12 13:33 UTC, msenechal commented on frontend/src/components/GraphViewModal.tsx
> +            console.error("Unable to retrieve document graph for " + inspectedName, results);
Can we have a state for error handling so we can feed that back to users with a banner saying something went wrong

2024-03-12 13:33 UTC, msenechal commented on frontend/src/components/GraphViewModal.tsx
> +            <InteractiveNvlWrapper
see comment above, so here we could display a danger/warning banner if there was an error while processing/getting/rendering the graph

2024-03-19 11:42 UTC, nielsdejong commented
To fix the issue with overlapping icons and node captions, we can use the new `captions` property of a node (as opposed to `caption` which we currently use):
https://didactic-garbanzo-oq54v33.pages.github.io/interfaces/Core.Node.html

Then, the `captionAlign` will have an effect:
![image](https://github.com/neo4j-labs/llm-graph-builder/assets/1754968/500df854-c5f8-429d-b914-85cbcdfdbf62)

here's an example of how to implement this:
https://github.com/neo-technology/neo4j-nevada/blob/main/packages/examples/src/exampleModules/test-examples/ReactWrapperWithCaptionsConfExample.jsx

2024-03-21 15:04 UTC, merged